// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHyxzhuUJCPT5h1L4gHqcGcwA0nj_YkWk',
    appId: '1:268712088877:web:5604b9959681e1e5d0efa4',
    messagingSenderId: '268712088877',
    projectId: 'to-do-codestcode',
    authDomain: 'to-do-codestcode.firebaseapp.com',
    storageBucket: 'to-do-codestcode.firebasestorage.app',
    measurementId: 'G-1SGMVDRF1E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsczjxq4ThQiKWvVXo720zge3hIth-tXg',
    appId: '1:268712088877:android:d645530af705c1afd0efa4',
    messagingSenderId: '268712088877',
    projectId: 'to-do-codestcode',
    storageBucket: 'to-do-codestcode.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0TLk2ia_sltFRyXTR9xSI5hTEn3asSo8',
    appId: '1:268712088877:ios:55f37e272dcfcebbd0efa4',
    messagingSenderId: '268712088877',
    projectId: 'to-do-codestcode',
    storageBucket: 'to-do-codestcode.firebasestorage.app',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0TLk2ia_sltFRyXTR9xSI5hTEn3asSo8',
    appId: '1:268712088877:ios:55f37e272dcfcebbd0efa4',
    messagingSenderId: '268712088877',
    projectId: 'to-do-codestcode',
    storageBucket: 'to-do-codestcode.firebasestorage.app',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHyxzhuUJCPT5h1L4gHqcGcwA0nj_YkWk',
    appId: '1:268712088877:web:d3fc57151c0f3501d0efa4',
    messagingSenderId: '268712088877',
    projectId: 'to-do-codestcode',
    authDomain: 'to-do-codestcode.firebaseapp.com',
    storageBucket: 'to-do-codestcode.firebasestorage.app',
    measurementId: 'G-7N2D9E436T',
  );
}
